apiVersion: v1
kind: Service
metadata:
  name: {{ include "catena.fullname" . }}
  labels:
    {{- include "catena.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    {{- include "catena.selectorLabels" . | nindent 4 }}
