name: Update README Examples Section

on:
  push:
    branches:
      - main
      - update-readme
    paths:
      - examples.json

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate README examples section
        shell: python
        run: |
          import json

          README_MD = "README.md"
          EXAMPLES_JSON = "examples.json"

          # load the examples data
          with open(EXAMPLES_JSON) as f:
              examples = json.load(f)
          # build the markdown content
          lines = []
          for conn in examples:
              lines.append(f"### {conn}")
              for ex in sorted(examples[conn]):
                  lines.append(f"- {ex}")
          # read the existing README
          with open(README_MD) as f:
              readme = f.read()
          # replace the section between the markers
          start_marker = "<!-- EXAMPLES_START -->"
          end_marker = "<!-- EXAMPLES_END -->"
          start_idx = readme.index(start_marker) + len(start_marker)
          end_idx = readme.index(end_marker)
          new_readme = readme[:start_idx] + "\n" + "\n".join(lines) + "\n" + readme[end_idx:]
          # write back the updated README
          with open(README_MD, "w") as f:
              f.write(new_readme)

      - name: Commit and push changes
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_EMAIL"
          git add README.md
          git commit -m "Update README examples section" || echo "No changes to commit"
          git push origin ${GITHUB_REF}